### ISSUE TITLE
Jina varianta grafu

### ISSUE THREAD

**Issue by radoslavius** [nanogreencz/homeassistant-integrations#8]
Trochu jsem si pohral s nastavenim grafu a rad bych jej nasdilel:

![image](https://github.com/nanogreencz/homeassistant-integrations/assets/3509024/11902647-cffb-401e-a941-fcbbff581f87)

```
type: custom:apexcharts-card
header:
  show: true
  title: Cena elektřiny dnes
  show_states: true
experimental:
  color_threshold: true
series:
  - entity: sensor.current_consumption_price_czk_kwh
    type: area
    name: Aktuální cena
    data_generator: |
      return entity.attributes.today_hourly_prices.map((price, index) => {
        const date = new Date()
        date.setHours(index)
        date.setMinutes(0)
        date.setSeconds(0)
        return [date.getTime(), price];
      });
    show:
      in_header: before_now
      extremas: true
all_series_config:
  color_threshold:
    - value: 1.5
      color: green
    - value: 2.5
      color: orange
    - value: 3.5
      color: red
graph_span: 24h
span:
  start: day
now:
  show: true
  label: Nyní
apex_config:
  chart:
    height: auto
  markers:
    size: 1
  xaxis:
    labels:
      hideOverlappingLabels: false
      datetimeFormatter:
        hour: HH
  stroke:
    show: true
    curve: stepline
    lineCap: butt
    colors: undefined
  yaxis:
    opposite: false
    reversed: false
    logarithmic: false
    decimalsInFloat: 0
    labels:
      show: true
    tooltip:
      enabled: true
    crosshairs:
      show: true
  grid:
    show: true
    strokeDashArray: 5
    xaxis:
      lines:
        show: true
```
